### ISSUE TITLE
not work now

### ISSUE THREAD

**Issue by ateproni** [tuyenldhust/proxy-stream-drive#2]
Hi... Great repo. I tried , but not work for now. How to change for work again?

**Comment by ledinhtuyen** [comment]
Code is still running. Can you post problem to here?

**Comment by ateproni** [comment]
Yes , code is running. Problem is not work to getlink failed. How to fix?

**Comment by ledinhtuyen** [comment]
Google has stopped streaming video from Google Driver by resolve reCaptcha
